import AnimatedText from '@/components/AnimatedText';
import Layout from '@/components/Layout';
import Head from 'next/head';
import React from 'react';

const Projects = () => {
    return (
        <>
        <Head>
        <title>Cindy Chassin | Projects page</title>
        <meta name="description" content="Generated by create next app" />
        </Head>
        <main className='w-full mb-16 flex flex-col items-center justify-center'>
        <Layout className='pt-16'>
            <AnimatedText text="Mes projets" />
        </Layout>
        </main>
        </>
    );
};

export default Projects;